language: scala
env:
  global:
    secure: iKV5GCxJh9hbQYTHM7cbcwYs0qGwEuIKVGPM/MPgvoeaMKbdrVatP+n1yhB5TSIrvLjssHu7VTQgxRQWgmS5t2s5RuTedfKlh6FtPvAByAwOiOVEU3N0Rj4TZ8PbrJOKzqY37fP13H3LeYgfV//DY3RBglRftvzTm1bKlTHmLfLD+WukC1LbbkYYu4brAGrQoiiNq2k4K6lVqdjL6HW4QBnL64vt72Y/gwXPc4DaODCZ956sxFGlA4UvltAJuge6KxdpaAZtO9SPE9HscAYEZzN6GV9IqFqXXR0v1LbRtbm5fDdFhjrqgIQUMz9VBhwUDJeBPC+IWCjMvEfIaRU18w9Vk3OVfu3+70RST8QcTCpk6xRW0AAmWNwLBS+gFknZX13e2j1VlhKzXk7Zqxib5RQqJX3lBOwKIeS+KO2wyq0z83/jvJdeewyfOroi/z/LK/NT9LvWs8VNInUw0lC/PKNSl2yCN7kn8dEAIZTZeGs1r/mMBPaWbh2oGGGi2oBk4aZYSIqhv9vKKW6WU13desFPeNOjoRsViwrW+77SKUrBlXaGgjPT4nsWva/ltnPIE1/J2t2LD3PTSyCsSFg6FgUiYkKjaYamglbmoWQ1jTqfK9fnXKZFsUdYJS7ubYI8lAg4rMEmPfLRvq0cjEWPXVALAbUim3sui/HuUczaBlM=
after_success: |
  if [ -n "$GITHUB_API_KEY" ]
    [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
    [ "$TRAVIS_BRANCH" == "master" ]; then

    echo -e "Publishing docs...\n"
    cp -R latest-docs/java $HOME/latest-javadoc
    cp -R latest-docs/scala $HOME/latest-scaladoc
    cd $HOME
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "travis-ci"
    git clone --quiet --branch=gh-pages https://${$GITHUB_API_KEY}@github.com/iuginP/pps-17-cw-mp gh-pages > /dev/null
    cd gh-pages
    git rm -rf ./java
    git rm -rf ./scala
    cp -Rf $HOME/latest-javadoc ./java
    cp -Rf $HOME/latest-scaladoc ./scala
    git add -f .
    git commit -m "Latest docs on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages"
    git push -fq origin gh-pages > /dev/null
    echo -e "Published docs to gh-pages.\n"
  fi
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$DOC_TOKEN"
  keep-history: true
  on:
    repo: iuginP/pps-17-cw-mp
    branch: gh-pages
deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file_glob: true
  file:
   - "releases/services/*"
   - "releases/clients/*"
   - "mobile/build/outputs/apk/*"
  skip_cleanup: true
  on:
    repo: iuginP/pps-17-cw-mp
    tags: true