language: scala
env:
  global:
    - secure: "aKodUbjXBS1Z6lIAMCgdSbuLY2SioVrnn3MqMkzp83xsibLbOlPSfEtdCGCdYXz9dzivtGu4u1yLltXWtYNgwGlVxevjOcapDC+QkLkZDExrhEyMb2Or6SObm7//XVT9pyhhXke2sun/gM04+OuBY0yAxnZEBONIaWD5WYHiLhnImTQaWY9xdn+tkNQCFJHySUYEgJ+ndT+/Yt9JDpAIJ5jP9wGlHT4GPY/3eqmMsdy895ceVGqkX6wdQstfyE90Sx8fqEp40pPHX1zkHTGlKi1H2O9SwaN2QyPyf77Qlb7XnCji2l490q9YE+FB/PSa3AYQzszkAqSJ9tcxh+eUsP+s9aFHyLZksfLUDppG7vJGjAZFbygnjDiFSDgTOaMiqVCyn7/5dnIVzaVOFWEP0cPgjKgCvaMGvxhiAAzW+GBYlgFErF6lh8/Cundz2OyTvq+hzYaQr19DbaMAcXkv0A66AOUgN6T43riZTh1TUKA4edOu7B6hTEWBATuatoUB09XP4Y+NtR2Uhbpu7q9PrA/ikVp7cmDH7n5xQCRmQuDS49capcaOvYUpna17ELv6fgWtXpzg8qsWlk54SSAs0ccol6SmS0NLVSgv5jmjABSGmxjLCf7QA34nhhOchyKWo0PCAuFEkw+P3RYaGYLLle/DuiF6PNPk+ruH39tMGvQ="
script:
  - './gradlew'
after_success:
  - 'bash scripts/commit_and_upload.sh -r iuginP/pps-17-cw-mp-tests -b master -s latest-docs/scala -d scala'
  - 'bash scripts/commit_and_upload.sh -r iuginP/pps-17-cw-mp-tests -b master -s latest-docs/java -d java'
  - 'bash scripts/commit_and_upload.sh -r iuginP/pps-17-cw-mp-tests -b master -s latest-docs/java -d scoverage report'
deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  skip_cleanup: true
  file_glob: true
  file: production/*
  on:
    repo: iuginP/pps-17-cw-mp-tests
    tags: true
