language: scala
env:
  global:
    - secure: "iO+XNd+oJ2Bp1VqIKHfjMwN+zPgvB357C+MO1Xw6BxbDv7hp76yNi3IanCBwM+rJVrc3AVtimOg+0QqJUa6BtPNNeSCMr5hny4UbJkWl9RPKJ7L5xT6hQFvVxmUAHkay2XMcwHmw091sbM5d/vfCbqYrBsmdqH7agyyo8xyEJ4RdY3ULh73QY88cVZOZGWhdYOw4ntkr7ugOvKon1K7Zp5zLXN2X19JmBMyAitvxlWfsiaaDVDz6OfgscfuREse4R/q70RvEUW3tPDswM5qFeJRp0t1WHyMFW9ZvRbspMFeu/vqcn1kJEIFT1JfUD/7CespAN1Ku+CXYMtel76LFuhtGkXBLtnREHIOFkW3/DfO1T4daRrR+4SmpGd6sC6CzcwvaIBtj+65NPuVg3Jvoy6t4s7p5SzFf/C4013jYTbjnDyuZVKb6VZXiFtClQbcdVIE0GJp9buSlJYvnYvAGNHBMD+RRPGhuS9o/MOfJC+xAOE/vMN8p4pQZbvT86NxvesrFyA1eelg2UGIRy+zmUjys82Z/Y90PMsCr3tzJQdnif5nlmoPdkHr9kWylH+K4T4V6ca5hdOSqP0+EL6Vflz4UO3zhkmXaLnGpKCAOQTIjfYm70hnhFVidbLis9PMKilZvU0Ql+X1UVZ9juckFQAcMVieBcmm/UQUYo3PuaQs="
script:
  - './gradlew'
after_success:
  - 'bash scripts/commit_and_upload.sh -r iugin/pps-17-cw-mp-tests -b MASTER -s /latest-docs/scala -d scala'
deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  skip_cleanup: true
  on:
    repo: iuginP/pps-17-cw-mp-tests
    tags: true
