language: scala
env:
  global:
    - secure: iKV5GCxJh9hbQYTHM7cbcwYs0qGwEuIKVGPM/MPgvoeaMKbdrVatP+n1yhB5TSIrvLjssHu7VTQgxRQWgmS5t2s5RuTedfKlh6FtPvAByAwOiOVEU3N0Rj4TZ8PbrJOKzqY37fP13H3LeYgfV//DY3RBglRftvzTm1bKlTHmLfLD+WukC1LbbkYYu4brAGrQoiiNq2k4K6lVqdjL6HW4QBnL64vt72Y/gwXPc4DaODCZ956sxFGlA4UvltAJuge6KxdpaAZtO9SPE9HscAYEZzN6GV9IqFqXXR0v1LbRtbm5fDdFhjrqgIQUMz9VBhwUDJeBPC+IWCjMvEfIaRU18w9Vk3OVfu3+70RST8QcTCpk6xRW0AAmWNwLBS+gFknZX13e2j1VlhKzXk7Zqxib5RQqJX3lBOwKIeS+KO2wyq0z83/jvJdeewyfOroi/z/LK/NT9LvWs8VNInUw0lC/PKNSl2yCN7kn8dEAIZTZeGs1r/mMBPaWbh2oGGGi2oBk4aZYSIqhv9vKKW6WU13desFPeNOjoRsViwrW+77SKUrBlXaGgjPT4nsWva/ltnPIE1/J2t2LD3PTSyCsSFg6FgUiYkKjaYamglbmoWQ1jTqfK9fnXKZFsUdYJS7ubYI8lAg4rMEmPfLRvq0cjEWPXVALAbUim3sui/HuUczaBlM=
script:
  - './gradlew'
after_success:
  - 'bash scripts/upload_docs.sh'
deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  skip_cleanup: true
  on:
    repo: iuginP/pps-17-cw-mp-tests
    tags: true
